Repository puppetlabs/beaker-pe, pull requests merged in 2023-05, with the labels that each got.

#211 (RE-15111) Add Mend Scanning
  .github/workflows/security.yml
  .github/workflows/snyk_merge.yaml
Labels: enhancement

#217 (RE-15478) Update actions and release workflow
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .github_changelog_generator
  CHANGELOG.md
  README.md
  release-prep
Labels: enhancement

#215 Allow beaker 5
  beaker-pe.gemspec
Labels: dependencies

#220 2.12.0 release prep and track lockfile
  .gitignore
  CHANGELOG.md
  Gemfile.lock
  lib/beaker-pe/version.rb
Labels: maintenance
